#pragma once

#include "error_t.h"

#define DARK_ERROR_VALUE_BASE			1102 * 666
#define DARK_ERROR_VALUE_MEMORY_EMPTY	DARK_ERROR_VALUE_BASE + 1
#define DARK_ERROR_VALUE_NOT_FOUNT		DARK_ERROR_VALUE_BASE + 100

#define DARK_ERROR_VALUE_SERVER_REJECT	DARK_ERROR_VALUE_BASE + 1000